[tool.poetry]
name = "hackathon"
version = "0.1.0"
description = ""
authors = ["geonwook"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.29.5"
jupyter = "^1.1.1"
polars = "^1.19.0"
pandas = "^2.2.3"
pyarrow = "^18.1.0"
scipy = "^1.15.1"
scikit-learn = "^1.6.1"
torch = "^2.5.1"
matplotlib = "^3.10.0"


[tool.poetry.group.dev.dependencies]
commitizen = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
